window.GALLERY_DATA = {
  "automotive": [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
    "12.jpg",
    "13.jpg",
    "14.jpg",
    "15.jpg",
    "16.jpg",
    "17.jpg",
    "18.jpg",
    "19.jpg",
    "20.jpg",
    "21.jpg",
    "22.jpg",
    "23.jpg",
    "24.jpg",
    "25.jpg",
    "26.jpg",
    "27.jpg",
    "28.jpg",
    "29.jpg",
    "30.jpg",
    "31.jpg",
    "32.jpg",
    "33.jpg",
    "34.jpg",
    "35.jpg",
    "36.jpg",
    "37.jpg",
    "38.jpg",
    "39.jpg",
    "40.jpg",
    "41.jpg",
    "42.jpg",
    "43.jpg",
    "44.jpg",
    "45.jpg",
    "46.jpg",
    "47.jpg",
    "48.jpg",
    "49.jpg"
  ],
  "hotel-interiors": [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
    "12.jpg",
    "13.jpg",
    "14.jpg",
    "15.jpg",
    "16.jpg",
    "17.jpg",
    "18.jpg",
    "19.jpg",
    "20.jpg",
    "21.jpg",
    "22.jpg",
    "23.jpg",
    "24.jpg",
    "25.jpg",
    "26.jpg",
    "27.jpg",
    "28.jpg",
    "29.jpg",
    "30.jpg",
    "31.jpg",
    "32.jpg",
    "33.jpg",
    "34.jpg",
    "35.jpg",
    "36.jpg",
    "37.jpg",
    "_P7A0134-Edit.jpg"
  ],
  "food-beverage": [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
    "12.jpg",
    "13.jpg",
    "14.jpg",
    "15.jpg",
    "16.jpg",
    "17.jpg",
    "18.jpg",
    "19.jpg",
    "20.jpg",
    "21.jpg",
    "22.jpg",
    "23.jpg"
  ],
  "events": [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
    "12.jpg",
    "13.jpg",
    "14.JPG",
    "15.jpg",
    "16.jpg",
    "17.jpg",
    "18.jpg",
    "19.jpg",
    "20.jpg",
    "21.jpg",
    "22.jpg",
    "23.jpg",
    "24.jpg",
    "25.jpg",
    "26.jpg",
    "27.jpg",
    "28.jpg",
    "29.jpg",
    "30.jpg",
    "31.jpg"
  ],
  "portrait-fashion": [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
    "12.jpg",
    "13.jpg",
    "14.jpg",
    "15.jpg",
    "16.jpg",
    "17.jpg",
    "18.jpg",
    "19.jpg",
    "20.jpg",
    "21.jpg",
    "22.jpg",
    "23.jpg",
    "24.jpg",
    "25.jpg",
    "26.JPG",
    "27.jpg"
  ],
  "sports": [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
    "12.jpg",
    "13.jpg",
    "14.jpg",
    "15.jpg",
    "16.jpg",
    "17.jpg",
    "18.jpg",
    "19.jpg",
    "20.jpg",
    "21.jpg",
    "22.jpg",
    "23.jpg",
    "24.jpg",
    "25.jpg",
    "26.jpg",
    "27.jpg",
    "28.jpg",
    "29.jpg",
    "30.jpg",
    "31.jpg",
    "32.jpg",
    "33.jpg",
    "34.jpg",
    "35.jpg",
    "36.jpg",
    "37.jpg"
  ]
};

window.GALLERY_ROW_PATTERNS = {
  "automotive": [3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3],
  "hotel-interiors": [3],
  "food-beverage": [4],
  "events": [3,4,6,5,3,6,4],
  "portrait-fashion": [3],
  "sports": [4,3,3,4,4,3,3,3,3,4]
};

window.CATEGORY_INFO = {
  "automotive": {
    "subtitle": "High-End Automotive Photography &amp; Prestige Vehicle Documentation",
    "section": "Automotive Photography Services in West Yorkshire",
    "copy": [
      "013 Create provides professional photography for the automotive industry, serving Leeds, Huddersfield, and the surrounding regions. Our portfolio includes editorial-style shoots for private commissions, standardised inventory photography for luxury showrooms, and high-detail documentation for specialist vehicle auctions.",
      "Using industry-leading equipment and advanced post-production techniques, we ensure every curve, texture, and finish is captured with absolute clarity. Whether it\u2019s a modern supercar, a vintage classic, or a commercial fleet, our photography is designed to drive engagement and elevate market presence. Based in West Yorkshire, we are available for location shoots and studio-based projects throughout the UK."
    ]
  },
  "hotel-interiors": {
    "subtitle": "Luxury Hospitality Media &amp; Bespoke Architectural Photography",
    "section": "Specialist Exterior &amp; Property Photography in West Yorkshire",
    "copy": [
      "013 Create provides professional architectural photography for the hospitality and real estate sectors across Leeds, Huddersfield, and the North of England. Our portfolio encompasses luxury hotel exteriors, commercial property showcases, and high-end residential documentation designed for editorial and marketing use.",
      "By utilising advanced perspective control and precision post-production, we ensure that every structure is presented with vertical accuracy and natural tonal balance. Whether it is a heritage hotel or a modern commercial development, our photography focuses on the intersection of light and form to create compelling visual narratives. Based in West Yorkshire, 013 Create is available for on-site commissions for architects, developers, and hospitality brands throughout the UK."
    ]
  },
  "food-beverage": {
    "subtitle": "Stylised Visuals for the Hospitality Sector",
    "section": "Commercial Food &amp; Beverage Photography | 013 Create",
    "copy": [
      "013 Create specialises in food and drink photography across Leeds, Huddersfield, and the North of England, offering high-end culinary imagery and beverage branding for restaurants, artisanal producers, and the hospitality sector \u2014 focusing on texture, colour, and composition.",
      "Employing precision lighting and bespoke food styling, our work covers editorial menu content, commercial packaging, and social media assets. From Michelin-starred menus to independent craft breweries, 013 Create offers on-site culinary photography and studio-based product shoots customised for hospitality industry needs."
    ]
  },
  "events": {
    "subtitle": "Commercial Event Photography &amp; Luxury Brand Activation Coverage",
    "section": "Professional Event Photographer in West Yorkshire",
    "copy": [
      "013 Create specialises in event photography across Leeds, Huddersfield, and northern England, offering comprehensive documentation for corporate conferences, luxury brand launches, and public activations. Our approach emphasises capturing both large-scale event moments and authentic candid interactions.",
      "Discreet, professional coverage ensures keynote speakers, branding details, and key deliverables are documented for PR, social media, and marketing purposes. Based in West Yorkshire, we accept commissions ranging from intimate gallery openings to multi-day commercial summits across the UK."
    ]
  },
  "portrait-fashion": {
    "subtitle": "Editorial Portraiture &amp; High-End Fashion Media Production",
    "section": "Portrait &amp; Fashion Photography West Yorkshire",
    "copy": [
      "Professional portraiture and fashion media production for brands, designers, and creative professionals across Leeds, Huddersfield, and the North of England. We specialise in high-end editorial fashion shoots, commercial lookbooks, and bespoke model portfolios, focusing on cinematic lighting and authentic storytelling.",
      "Whether delivering studio-based campaigns or environmental portraits on location, our work is defined by technical excellence. Based in West Yorkshire, 013 Create provides specialised photography services designed to elevate brand identity and creative presence for clients throughout the UK."
    ]
  },
  "sports": {
    "subtitle": "Action Sports Photography &amp; Dynamic Athlete Content Creation",
    "section": "Action Sports &amp; Athlete Photography West Yorkshire",
    "copy": [
      "Professional sports media and high-performance athlete photography serving Leeds, Huddersfield, and the wider North of England. We specialise in capturing the raw energy and technical precision of action sports, providing stills for commercial branding, editorial features, and professional athlete portfolios.",
      "From motorsports and field athletics to action sports campaigns, our work focuses on dynamic composition. Based in West Yorkshire, 013 Create delivers elite visual assets for clubs, individual athletes, and sports brands, ensuring every decisive moment is documented with clarity and impact for marketing and PR use across the UK."
    ]
  }
};

/* Per-image crop overrides — default is "center center".
   Set "center bottom" for images whose subject sits in the lower portion of the frame. */
window.GALLERY_POSITIONS = {
  "automotive": {
    "16.jpg": "center bottom",
    "20.jpg": "center 70%",
    "26.jpg": "center bottom"
  },
  "hotel-interiors": {
    "2.jpg":  "center bottom",
    "18.jpg": "center 20%"
  },
  "food-beverage": {
    "1.jpg":  "center 40%",
    "4.jpg":  "center 60%",
    "18.jpg": "center 60%",
    "23.jpg": "center 60%"
  },
  "sports": {
    "2.jpg":  "center 70%",
    "3.jpg":  "center 65%",
    "15.jpg": "center 65%",
    "16.jpg": "center bottom",
    "22.jpg": "center bottom"
  }
};

/* ─────────────────────────────────────────────────────────────────
   GALLERY_ALT_TEXT — per-image alt text for SEO and accessibility
   ─────────────────────────────────────────────────────────────────
   HOW TO USE:
   Add an entry for any image that deserves a specific description.
   Key = exact filename (must match GALLERY_DATA above).
   Value = a descriptive sentence: what vehicle/subject, any notable
   details, location. Keep under 125 characters.

   Images without an entry here will fall back to the category-level
   alt text in gallery.js automatically.

   EXAMPLE:
     "automotive": {
       "1.jpg": "Red Ferrari 488 GTB detail shot — carbon fibre wing mirror, West Yorkshire countryside background",
       "2.jpg": "Porsche 911 GT3 RS in Lava Orange at golden hour, Yorkshire Dales — 013Create automotive photography"
     }
   ───────────────────────────────────────────────────────────────── */
window.GALLERY_ALT_TEXT = {
  "automotive": {
    "1.jpg": "Ferrari 599XX widebody in red — night urban shoot with light trails, editorial supercar photography UK by 013Create",
    "2.jpg": "Ferrari 599XX GTO in Rosso Corsa at golden hour in open Yorkshire field — prestige supercar photography UK",
    "3.jpg": "Ferrari 599XX GTO rear three-quarter — atmospheric smoky carpark, prestige automotive photography UK by 013Create",
    "4.jpg": "Audi Sport Quattro S1 Group B rally car — forest stage action with dust cloud, classic motorsport photography UK",
    "5.jpg": "Audi Sport Quattro S1 Group B rally car — golden hour forest stage with dust and sunbeams, motorsport photography",
    "6.jpg": "Lamborghini Huracán STO carbon fibre race car — moody architectural interior setting, prestige supercar photography UK",
    "7.jpg": "Lamborghini Huracán STO side profile — dark concrete architectural environment, luxury supercar photography UK",
    "8.jpg": "Lamborghini Huracán STO rear view — stormy architectural backdrop, carbon fibre detail, racing photography UK",
    "9.jpg": "Porsche 911 GT3 RS rear view at sunset — Yorkshire Dales moorland road, prestige car photography by 013Create",
    "10.jpg": "Porsche 911 GT3 RS in black at golden hour — puddle reflection, Yorkshire Dales dry-stone wall, supercar photography",
    "11.jpg": "Porsche 911 GT3 RS front three-quarter at sunrise — Yorkshire moorland road, prestige automotive photography UK",
    "12.jpg": "Female model leaning on red Ferrari-badged Fiat 500 — Caffe Grande Piccolino, lifestyle automotive photography",
    "13.jpg": "Female model driving vintage red Fiat 500 interior — city rooftop, lifestyle automotive portrait photography",
    "14.jpg": "Female model with red Ferrari Fiat 500 on rooftop — city skyscrapers background, lifestyle automotive shoot",
    "15.jpg": "Orange Peugeot 2008 GT Line in front of Tyne Bridge Newcastle at sunset — commercial vehicle photography UK",
    "16.jpg": "Orange Peugeot 2008 GT Line on cobbled street — UK heritage brick building, commercial automotive photography",
    "17.jpg": "Orange Peugeot 2008 GT Line in pine forest at golden hour — atmospheric commercial vehicle photography UK",
    "18.jpg": "Red Bull BMX athlete performing wall ride above red Peugeot 208 — action sports brand campaign photography",
    "19.jpg": "Red Bull BMX athlete beside red Peugeot 208 at urban skate park — lifestyle commercial photography UK",
    "20.jpg": "Silver Peugeot 508 at solar-canopy EV charging station — electric vehicle commercial photography UK",
    "21.jpg": "Land Rover Defender Talos edition in white — rose-gold dusk on Yorkshire moorland, luxury 4x4 photography UK",
    "22.jpg": "Land Rover Defender Talos in white — ornate gate exterior setting, prestige SUV photography UK by 013Create",
    "23.jpg": "Land Rover Defender Talos front-wheel detail — Yorkshire countryside close-up, luxury SUV automotive photography",
    "24.jpg": "Red Bull BMX athlete wall-riding above red Peugeot 208 — commercial sports-lifestyle brand photography UK",
    "25.jpg": "Red Bull BMX rider relaxing beside red Peugeot 208 at skate park — commercial lifestyle automotive photography",
    "26.jpg": "Silver Peugeot 508 under solar canopy — EV charging station, Wingrove Peugeot commercial photography UK",
    "27.jpg": "DS 9 luxury saloon in blue driving through misty forest — Wingrove Motor Company commercial photography UK",
    "28.jpg": "DS 9 luxury saloon blue side profile — foggy woodland road, editorial automotive photography UK by 013Create",
    "29.jpg": "DS 9 luxury interior — premium white quilted leather, central infotainment, commercial automotive photography",
    "30.jpg": "Sage green DS 3 Crossback with woman and dog — woodland lane, Wingrove lifestyle automotive photography UK",
    "31.jpg": "Red DS 3 Crossback — misty Yorkshire hillside with white fence, editorial automotive photography UK",
    "32.jpg": "Citroën C5 Aircross interior detail — steering wheel and touchscreen, commercial automotive photography UK",
    "33.jpg": "White Ford RS200 Talos edition on runway — classic Group B rally car documentation photography UK",
    "34.jpg": "White Ford RS200 Talos front arch detail — period alloys, classic Group B motorsport photography UK",
    "35.jpg": "White Ford RS200 Talos rear three-quarter on runway — classic rally car photography UK by 013Create",
    "36.jpg": "Porsche 911 GT2 RS in black — moody mist over Yorkshire moors, prestige supercar photography UK",
    "37.jpg": "Porsche 911 GT2 RS carbon fibre rear with gold BBS wheels — close-up garage detail, automotive photography UK",
    "38.jpg": "Porsche 911 GT2 RS under blue-violet neon in dark hangar — alongside Ford RS200, atmospheric automotive photography",
    "39.jpg": "McLaren MP4/4 Formula 1 Marlboro car — dramatic concrete architectural setting, classic F1 photography UK",
    "40.jpg": "McLaren MP4/4 Formula 1 car body detail — Marlboro livery close-up, dark studio motorsport photography",
    "41.jpg": "Red Ferrari Fiat 500 driver's window detail — female hands on white steering wheel, automotive detail photography",
    "42.jpg": "Land Rover Defender Talos in white — dramatic aircraft hangar with blue overhead lighting, luxury SUV photography",
    "43.jpg": "Racing driver in yellow and pink livery seated against Lamborghini Huracán GT3 Evo — motorsport portrait photography",
    "44.jpg": "Audi Quattro Sport S1 Group B in full livery — mountain alpine dawn light, classic rally car photography",
    "45.jpg": "Ford Ranger Raptor Talos at dawn — vast moorland landscape with horses, commercial truck photography UK",
    "46.jpg": "Porsche 911 Carrera in silver — green countryside parkland side profile, prestige car photography UK",
    "47.jpg": "Audi e-tron electric SUV in blue driving past mountain lake — EV commercial photography by 013Create",
    "48.jpg": "Sunseeker luxury motor yacht close-up — white hull and superstructure against teal sky, marine photography",
    "49.jpg": "Sunseeker luxury motor yacht underway — Mediterranean coastal backdrop, luxury marine photography"
  },
  "hotel-interiors": {
    "1.jpg": "Royal British Hotel Edinburgh exterior — heritage sandstone facade with light trails, hospitality architecture photography",
    "2.jpg": "Spanish City Whitley Bay illuminated at night under stars — landmark hospitality architecture photography UK",
    "3.jpg": "Spanish City Whitley Bay at night — dramatic blue light trails past restored dome, architecture photography UK",
    "4.jpg": "The Catalyst Building Newcastle — distinctive geometric timber-clad facade at dusk, commercial architecture photography",
    "5.jpg": "The Catalyst Building interior lobby signage — framed by geometric timber structure, architectural detail photography",
    "6.jpg": "Spanish City Whitley Bay dome interior — ornate gold swag decor and balcony, heritage hospitality photography UK",
    "7.jpg": "Spanish City Whitley Bay — ornate white dome ceiling looking up, architectural heritage interior photography UK",
    "8.jpg": "Grand hotel restaurant — gold velvet banquette seating and crystal chandeliers, luxury hospitality photography UK",
    "9.jpg": "Ice bar interior — glowing ice furniture, sculptures and bar, unique luxury venue photography UK by 013Create",
    "10.jpg": "Luxury hotel spa — indoor heated pool with starlit LED ceiling, sauna rooms visible, spa photography UK",
    "11.jpg": "Luxury hotel spa jacuzzi — glowing purple LED mosaic tiles with spa branding, hotel spa photography UK",
    "12.jpg": "Luxury hotel spa — couple beside starlit indoor pool, lifestyle hospitality photography UK by 013Create",
    "13.jpg": "Luxury hotel spa indoor pool — full-width view with starlit ceiling and treatment rooms, architectural photography",
    "14.jpg": "Luxury hotel spa — couple relaxing poolside in robes, lifestyle hospitality photography UK",
    "15.jpg": "Boutique hotel lounge — corniced corridor with velvet armchairs and framed art, luxury UK hotel photography",
    "16.jpg": "Hotel spa treatment room — therapist performing massage by candlelight, luxury spa photography UK by 013Create",
    "17.jpg": "Medieval castle living room — snooker table, wood-burning stove and large-format artwork, luxury let photography",
    "18.jpg": "Boutique hotel bedroom — dark patterned wallpaper with glowing cage pendant light, moody interior photography UK",
    "19.jpg": "Medieval castle interior — vaulted sitting room with wood burner and leaded windows, luxury holiday photography",
    "20.jpg": "Contemporary A-frame woodland lodge exterior at golden hour — luxury holiday accommodation photography UK",
    "21.jpg": "Luxury A-frame woodland lodge at night — illuminated timber exterior with hot tub under stars",
    "22.jpg": "Luxury woodland lodge with hot tub at night — illuminated exterior under starry sky, holiday property photography",
    "23.jpg": "Luxury spa outdoor plunge pool at sunrise — snowy Yorkshire countryside panorama, hotel spa photography UK",
    "24.jpg": "Luxury holiday cottage sitting room — blue velvet chair, wood burner, exposed timber beams",
    "25.jpg": "Luxury barn conversion interior — open-plan with glazed vaulted roof and stone walls, holiday property photography",
    "26.jpg": "Luxury holiday cottage bedroom — vaulted ceiling with golden globe pendant light, property photography UK",
    "27.jpg": "Boutique hotel bedroom — round mirror reflecting patterned headboard and lamp, interior photography UK",
    "28.jpg": "Luxury country house ensuite bedroom — gold tap marble basin and blossom wallpaper, interiors photography UK",
    "29.jpg": "Hilton hotel grand lobby — ornate marble columns, ceiling murals and chandelier, luxury hospitality photography",
    "30.jpg": "Hilton hotel lobby corridor — marble columns and murals, luxury hotel interior photography UK by 013Create",
    "31.jpg": "Industrial-chic restaurant interior — turquoise banquettes and Edison pendant lights, hospitality photography UK",
    "32.jpg": "Entertainment venue interior — pool tables and arcade machines under industrial lighting, venue photography UK",
    "33.jpg": "Luxury Stonebrdige kitchen — wall-mounted TV and Bang & Olufsen soundbar, minimalist interior photography",
    "34.jpg": "Designer bathroom gold articulated tap — running water over book-matched dark marble, luxury interior photography",
    "35.jpg": "Luxury kitchen walnut drawer detail — black cutlery with brass handles, high-end interior photography UK",
    "36.jpg": "Armani/Roca luxury bathroom display — gold mixer tap and white basin with amber wall lights, showroom photography",
    "_P7A0134-Edit.jpg": "Luxury hotel spa courtyard — couple in robes drinking champagne in rattan pod, UK hotel photography by 013Create"
  },
  "food-beverage": {
    "1.jpg": "Pan-fried seabass on marble plate with white wine glass — fine dining food photography UK by 013Create",
    "2.jpg": "Mixed grill sharing board — rack of ribs, king prawns, corn and steak on wood, restaurant photography UK",
    "3.jpg": "Gourmet burger with chips in dark pub setting — commercial food photography UK by 013Create",
    "4.jpg": "Strawberry and basil smash cocktail in highball glass — colourful bar background, drinks photography UK",
    "5.jpg": "Hard Rock Cafe Legend burger with fries — brioche bun with branded knife, restaurant food photography UK",
    "6.jpg": "Chef cracking sugar meringue dessert at marble dining table — fine dining action food photography UK",
    "7.jpg": "Irn-Bru cocktail with orange twist and ice — golden bar background, Scottish bar beverage photography",
    "8.jpg": "Double cheeseburger pulled apart cross-section — pub restaurant food photography UK by 013Create",
    "9.jpg": "Cheese sauce poured over smashed burger — dark pub backdrop, commercial restaurant food photography UK",
    "10.jpg": "Loaded nachos in branded paper wrapper — street food restaurant photography UK by 013Create",
    "11.jpg": "Woman biting into loaded hot dog — dark restaurant, lifestyle food photography UK",
    "12.jpg": "Espresso martini in coupe glass — dark wood bar surface, cocktail photography UK by 013Create",
    "13.jpg": "Chocolate mousse dessert with ice cream scoops and wine glasses — fine dining photography UK",
    "14.jpg": "Overhead raspberry cream dessert on ornate gold wire table — fine dining food photography UK by 013Create",
    "15.jpg": "White wine being poured at fine dining table — Growers Gate bottle, restaurant beverage photography UK",
    "16.jpg": "Frederick's restaurant menu cover — gold foil embossed branding on dark cover, luxury hospitality photography",
    "17.jpg": "Cocktails and sliders at ornate hotel bar — gin balloon and mojito with small plates, hospitality photography UK",
    "18.jpg": "Gourmet burgers with cocktails on serving boards — grand Hilton hotel dining room, luxury food photography UK",
    "19.jpg": "Grilled Cajun chicken salad with quinoa — Carters Champagne Bar branded plate, restaurant food photography UK",
    "20.jpg": "Braised beef short rib with giant Yorkshire pudding and gravy being poured — pub food photography UK",
    "21.jpg": "Roast dinner with giant Yorkshire pudding — eclectic colourful restaurant interior, pub food photography UK",
    "22.jpg": "Dessert selection of four plates including crème brûlée and chocolate brownie — Hard Rock Cafe food photography",
    "23.jpg": "Slow-roasted lamb with Yorkshire pudding and gravy poured at table — restaurant dining photography UK"
  },
  "events": {
    "1.jpg": "Live music concert — packed indoor venue with stage lighting and full crowd, event photography UK by 013Create",
    "2.jpg": "Hip-hop artist performing on stage — black and white low-angle concert photography UK",
    "3.jpg": "Hip-hop band full lineup on stage with DJ, guitarist and vocalist — energetic concert photography UK",
    "4.jpg": "Hip-hop artist with microphone on stage — red stage lighting low-angle, live music photography UK",
    "5.jpg": "DJ mixing on Pioneer decks — nightclub red lighting, music event photography UK by 013Create",
    "6.jpg": "Tattooed artist performing with microphone — blue and purple stage lighting, live music photography UK",
    "7.jpg": "Musician playing Fender Stratocaster close-up — black and white, live music event photography UK",
    "8.jpg": "Young guitarist playing pale blue electric guitar — dark stage, indie band concert photography UK",
    "9.jpg": "Singer performing passionately on stage — purple lighting with guitarist behind, band event photography UK",
    "10.jpg": "Guitarist playing red electric guitar — warm amber stage lighting, indie band photography UK",
    "11.jpg": "Electric guitarist on stage — blue and purple lighting, indie live music photography UK by 013Create",
    "12.jpg": "Aerial view of Hardwick Hall estate with event tents beside lake — drone event photography UK",
    "13.jpg": "Talos Vehicles military truck transporting McLaren MP4/4 F1 car on UK motorway — automotive event photography",
    "14.jpg": "McLaren Formula 1 driver signing autograph for fan — Goodwood Festival of Speed, motorsport event photography",
    "15.jpg": "Guests at prestige automotive event — Porsche 911 GT3 on display, Talos Vehicles showcase photography UK",
    "16.jpg": "Colin McRae Subaru Impreza WRC paddock scene — Goodwood Festival of Speed classic motorsport photography",
    "17.jpg": "Colin McRae Subaru Impreza WRC in pit lane at golden hour — Goodwood Festival of Speed atmosphere shot",
    "18.jpg": "Colin McRae Subaru Impreza WRC running up the Goodwood hillclimb — action motorsport event photography UK",
    "19.jpg": "Classic car social event — Ferrari 599XX and Fiat 500 at country house, automotive outdoor event photography",
    "20.jpg": "Ferrari 599XX and Porsche 911 at automotive show — spectators at Talos Vehicles stand, car event photography UK",
    "21.jpg": "Classic Ferrari Fiat 500 and vintage Mini at country house — festoon lighting, classic car event photography",
    "22.jpg": "Ferrari 599XX and Porsche 911 GT2 RS at indoor automotive show — Talos Vehicles exhibition stand photography",
    "23.jpg": "Porsche 911 GT2 RS detail beside McLaren MP4/4 on transporter — car show exhibition photography UK",
    "24.jpg": "Crowd walking past red Ferrari 599XX at Talos Vehicles stand — automotive show event photography UK",
    "25.jpg": "Couple admiring carbon Porsche 911 GT2 RS at Goodwood Revival — Talos Vehicles hospitality tent photography",
    "26.jpg": "Women toasting champagne beside Bugatti at hospitality suite — prestige automotive event photography UK",
    "27.jpg": "Porsche 911 GT2 RS carbon on display in hospitality tent at Goodwood Revival — prestige event photography",
    "28.jpg": "Judges seated at outdoor awards ceremony — grand country estate, corporate event photography UK by 013Create",
    "29.jpg": "Presenter with trophies at outdoor concours awards podium — prestige automotive event photography UK",
    "30.jpg": "Two men networking at hospitality event — fist bump, corporate event photography UK by 013Create",
    "31.jpg": "Red Ferrari 599XX at Aviva concours d'elegance judging — prestige classic car event photography UK"
  },
  "portrait-fashion": {
    "1.jpg": "Red Bull athlete in branded cap — dramatic moody car interior portrait photography UK by 013Create",
    "2.jpg": "Female dancer silhouette at golden hour sunset on beach — dynamic ballet-style lifestyle portrait photography",
    "3.jpg": "Ballet dancer pointe shoes on wooden jetty at sunset — close-up detail portrait photography UK",
    "4.jpg": "Man blowing dandelion seeds in meadow at golden hour — lifestyle portrait photography UK by 013Create",
    "5.jpg": "Racing driver in full race suit and helmet beside Lamborghini GT3 Evo — motorsport editorial portrait photography",
    "6.jpg": "TIG welder close-up with arc light — dramatic industrial trades portrait photography UK by 013Create",
    "7.jpg": "Female model in white shirt with red Ferrari Fiat 500 — rooftop car park, lifestyle fashion portrait photography",
    "8.jpg": "Female model in red Fiat 500 through driver's window — lifestyle automotive portrait photography UK",
    "9.jpg": "Female model driving vintage red Fiat 500 — designer sunglasses, city skyline, lifestyle portrait photography",
    "10.jpg": "Female model leaning on red Ferrari Fiat 500 — Caffe Grande Piccolino, lifestyle fashion photography UK",
    "11.jpg": "Female athlete stretching beside Ford Ranger Raptor — fitness lifestyle photography UK by 013Create",
    "12.jpg": "Talos-branded tumbler held over Ford Ranger Raptor Talos centre console — lifestyle product photography UK",
    "13.jpg": "Female model adjusting sunglasses in rearview mirror — DS3, Leeds city skyline, automotive lifestyle portrait",
    "14.jpg": "Male fabricator working on automotive carbon panel in workshop — professional trades portrait photography UK",
    "15.jpg": "Metal fabricator grinding with sparks — dramatic action portrait, professional trades photography UK",
    "16.jpg": "Contemplative man portrait — black and white with colourful clothing rack background, fashion portrait UK",
    "17.jpg": "Aztec Diamond Equestrian leather saddle on grey horse — equestrian brand product photography UK",
    "18.jpg": "Female equestrian rider on grey horse trotting in arena — Aztec Diamond Equestrian product photography UK",
    "19.jpg": "Show jumping horse and rider clearing fence — Aztec Diamond Equestrian action photography UK by 013Create",
    "20.jpg": "Male chef flambéing in professional kitchen — dramatic fire and motion, hospitality portrait photography UK",
    "21.jpg": "Welder with Lincoln welding mask and blue arc — competition welding, professional trades photography UK",
    "22.jpg": "Male model in navy workwear fleece — industrial truck backdrop, commercial workwear fashion photography UK",
    "23.jpg": "Female model in green polo shirt — Case IH tractor background, commercial workwear photography UK",
    "24.jpg": "Female equestrian model in Aztec Diamond base layer — white studio side profile, equestrian fashion photography",
    "25.jpg": "Female equestrian model in Aztec Diamond zip-neck top — clean white studio portrait, equestrian fashion UK",
    "26.jpg": "Hip-hop artist in white textured hoodie with gold chains — dark background moody portrait photography UK",
    "27.jpg": "Off-White x Converse Chuck Taylor All Stars detail — on stage at live concert, sneaker fashion photography"
  },
  "sports": {
    "1.jpg": "Wakeboarder performing inverted aerial trick — Mediterranean mountains backdrop, action watersports photography UK",
    "2.jpg": "Skier jumping mogul at alpine resort at sunset — mountain backdrop, action skiing photography UK by 013Create",
    "3.jpg": "Freestyle skier carving in powder snow — wide blue sky alpine landscape, action skiing photography",
    "4.jpg": "Windsurfer launching off wave — clear Mediterranean sea, action watersports photography UK by 013Create",
    "5.jpg": "Mountain biker on gravel trail — puddle reflection and mountainous backdrop, adventure cycling photography",
    "6.jpg": "Two wakeboarders simultaneously — one airborne and one wake surfing, Mediterranean action sports photography",
    "7.jpg": "Golfer teeing off at Porsche Golf Day — Close House Newcastle, commercial golf event sports photography",
    "8.jpg": "Two golfers shaking hands at Close House golf course — corporate sports event photography UK by 013Create",
    "9.jpg": "Newcastle United footballer walking pitch at St James' Park — Premier League football photography UK",
    "10.jpg": "St James' Park interior empty under floodlights — wide-angle pitch-level stadium photography Newcastle United",
    "11.jpg": "Newcastle Eagles basketball player dunking at the hoop — BBL British Basketball League action photography UK",
    "12.jpg": "Newcastle Eagles players high-fiving on court — BBL British Basketball League game photography UK",
    "13.jpg": "Newcastle Eagles player #44 dribbling through defence — BBL basketball action photography UK by 013Create",
    "14.jpg": "Newcastle Eagles player #44 walking court — BBL British Basketball League player photography UK",
    "15.jpg": "BMX rider performing aerial at skatepark at night — black and white fish-eye extreme sports photography UK",
    "16.jpg": "Female sailor on Neilson dinghy — Mediterranean coastline, watersports holiday sailing photography",
    "17.jpg": "Dinghy sailing in choppy water close-up — Hummingbird class, action watersports photography",
    "18.jpg": "Smiling wakeboarder riding at speed — Mediterranean beach backdrop, action watersports photography",
    "19.jpg": "Road cyclist in high-visibility kit — Mediterranean countryside backdrop, sports cycling photography",
    "20.jpg": "Wakeboarder riding wave on orange board — Mediterranean bay, action wakeboarding photography",
    "21.jpg": "Kitesurfer on hydrofoil board — Mediterranean coastline backdrop, kitesurfing action photography",
    "22.jpg": "Wakeboarder performing Donix-board aerial — Mediterranean mountains, action watersports photography UK",
    "23.jpg": "Three Neilson dinghies racing in formation — Mediterranean sea, competitive sailing photography",
    "24.jpg": "Female water skier carving wake — Mediterranean open sea, action watersports photography by 013Create",
    "25.jpg": "Snowboarder grinding box at Val Thorens snowpark — alpine action snowboarding photography France",
    "26.jpg": "Snowboarder in giant slalom race gates — Val Thorens alpine competition photography",
    "27.jpg": "Three Neilson dinghies sailing — glittering Mediterranean horizon, sailing sports photography",
    "28.jpg": "Kayaker surfing ocean wave — red helmet and orange kayak, action watersports photography",
    "29.jpg": "Windsurfer pulling high aerial manoeuvre — red sail, Mediterranean sea, extreme watersports photography",
    "30.jpg": "Windsurfer carving wave in chop — red sail with desert coastline, action watersports photography",
    "31.jpg": "Giant slalom skier in colourful suit — alpine race gates at alpine resort, competition skiing photography",
    "32.jpg": "Three dinghies sailing on glittering Mediterranean — minimalist wide-angle sailing photography",
    "33.jpg": "Tennis player hitting backhand shot — Babolat branded court, action tennis sports photography",
    "34.jpg": "Tennis player returning serve on outdoor clay court — action sports photography UK by 013Create",
    "35.jpg": "Windsurfer riding large wave — open ocean, extreme watersports action photography",
    "36.jpg": "Newcastle United vs Burnley players walking off pitch — St James' Park Premier League football photography",
    "37.jpg": "Newcastle United vs Burnley aerial header from corner — St James' Park, Premier League football photography UK"
  }
};
